"""empty message

Revision ID: 0a54c04a4aa8
Revises: 
Create Date: 2024-11-18 14:01:23.507285

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0a54c04a4aa8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("password", sa.String(length=100), nullable=False),
        sa.Column("mfa_key", sa.String(length=32), nullable=False),
        sa.Column("mfa_enabled", sa.Boolean(), nullable=False),
        sa.Column("role", sa.String(length=100), nullable=False),
        sa.Column("firstname", sa.String(length=100), nullable=False),
        sa.Column("lastname", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=100), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("salt", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("userid", sa.Integer(), nullable=True),
        sa.Column("registered_on", sa.DateTime(), nullable=False),
        sa.Column("latest_login", sa.DateTime(), nullable=True),
        sa.Column("previous_login", sa.DateTime(), nullable=True),
        sa.Column("latest_ip", sa.String(length=100), nullable=True),
        sa.Column("previous_ip", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["userid"], ["users.id"], name=op.f("fk_logs_userid_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_logs")),
    )
    op.create_table(
        "posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("userid", sa.Integer(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["userid"], ["users.id"], name=op.f("fk_posts_userid_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_posts")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("posts")
    op.drop_table("logs")
    op.drop_table("users")
    # ### end Alembic commands ###
