"""empty message

Revision ID: 4f2eff86f627
Revises: 65377a55975c
Create Date: 2024-11-11 14:00:49.391832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f2eff86f627'
down_revision = '65377a55975c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('registration', sa.DateTime(), nullable=False),
    sa.Column('latest_login', sa.DateTime(), nullable=True),
    sa.Column('previous_login', sa.DateTime(), nullable=True),
    sa.Column('latest_ip', sa.String(length=100), nullable=True),
    sa.Column('previous_ip', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], name=op.f('fk_logs_userid_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_logs'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    # ### end Alembic commands ###
