"""empty message

Revision ID: 65377a55975c
Revises: a0a9bdbdf58e
Create Date: 2024-10-29 21:08:01.198789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65377a55975c'
down_revision = 'a0a9bdbdf58e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
