"""empty message

Revision ID: b0e26d6b33f0
Revises: 4f2eff86f627
Create Date: 2024-11-11 14:14:08.309351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0e26d6b33f0'
down_revision = '4f2eff86f627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registered_on', sa.DateTime(), nullable=False))
        batch_op.drop_column('registration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration', sa.DATETIME(), nullable=False))
        batch_op.drop_column('registered_on')

    # ### end Alembic commands ###
