"""empty message

Revision ID: ecc2254502e8
Revises: 71531512d060
Create Date: 2024-10-22 12:46:39.875064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecc2254502e8'
down_revision = '71531512d060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mfa_key', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('mfa_enabled', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mfa_enabled')
        batch_op.drop_column('mfa_key')

    # ### end Alembic commands ###
